service: mccall-bot

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: go1.x
  memorySize: 128
  timeout: 30
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    - "arn:aws:iam::aws:policy/ComprehendReadOnly"
  logs:
    restApi: true

functions:
  talk:
    handler: bin/talk
    events:
      - http:
          path: talk
          method: post
    environment: ${file(./conf/${opt:stage}.yml)}

package:
  exclude:
    - ./**
  include:
    - ./bin/**
