service: mccall-bot

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  talk:
    handler: bin/talk
    events:
      - http:
          path: talk
          method: post
    environment: ${file(./conf/env.yml)}

package:
  exclude:
    - ./**
  include:
    - ./bin/**
